//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoStorage.Persistence.Tests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TodoStorageSeedContext : DbContext
    {
        public TodoStorageSeedContext()
            : base("name=TodoStorageSeedContext")
        {
            TodoItems = Set<TodoItem>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<TodoItem> TodoItems { get; set; }
        public virtual DbSet<AuthenticationItem> AuthenticationItems { get; set; }
    }
}
